//
//  BubbleStyleKit.h
//  Lumi Connect v2
//
//  Created by Martin Kuvandzhiev on 6/6/16.
//  Copyright (c) 2016 Rapid Development Crew. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface BubbleStyleKit : NSObject

// Colors
+ (UIColor*)shadowColor;
+ (UIColor*)redOuter;
+ (UIColor*)redInner;
+ (UIColor*)greenOuter;
+ (UIColor*)greenInner;
+ (UIColor*)blueOuter;
+ (UIColor*)blueInner;
+ (UIColor*)cyanOuter;
+ (UIColor*)cyanInner;
+ (UIColor*)purpleInner;
+ (UIColor*)purpleOuter;

// Drawing Methods
+ (void)drawLumiViewWithInnerCircleColor: (UIColor*)innerCircleColor outerCircleColor: (UIColor*)outerCircleColor innerTextString: (NSString*)innerTextString viewFrame: (CGRect)viewFrame;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
