source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!
target 'Lumi-iOS' do
#    pod "SAConfettiView"
    pod 'BButton'
#    pod 'SCLAlertView'
#    pod 'Firebase'
    pod 'Firebase/Crash'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Database'
    pod 'SCLAlertView-Objective-C'
    pod 'Google/Analytics'
    pod 'Fabric'
    pod 'Crashlytics'
    
    
    
end
